# Generated by Django 4.0.5 on 2022-06-20 04:22

from django.db import migrations, models
import django.utils.timezone
import watch.models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=watch.models.user_directory_path, verbose_name='Picture'),
            preserve_default=False,
        ),
    ]
