# Generated by Django 4.0.5 on 2022-06-20 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import watch.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watch', '0004_alter_post_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighbourHood',
            fields=[
                ('neighborhood_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to=watch.models.user_directory_path)),
                ('location', models.CharField(max_length=100)),
                ('occupants_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
