# Generated by Django 4.0.4 on 2022-06-20 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0005_neighbourhood'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NeighbourHood',
        ),
    ]
