# Generated by Django 4.0.4 on 2022-06-20 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import watch.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watch', '0006_delete_neighbourhood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('neighborhood_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to=watch.models.user_directory_path, verbose_name='Picture')),
                ('location', models.TextField(max_length=300, verbose_name='Caption')),
                ('occupants_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
