# Generated by Django 4.0.4 on 2022-06-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0007_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='location',
            field=models.TextField(max_length=300, verbose_name='Location'),
        ),
    ]
