# Generated by Django 4.0.4 on 2022-06-20 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0011_rename_email_address_business_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='neighborhood_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watch.neighborhood'),
        ),
    ]
