# Generated by Django 4.0.4 on 2022-06-20 20:40

from django.db import migrations, models
import django.db.models.deletion
import watch.models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0012_alter_business_neighborhood_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to=watch.models.user_directory_path, verbose_name='Picture')),
                ('contact_info', models.CharField(max_length=100)),
                ('neighborhood_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watch.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='HealthCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to=watch.models.user_directory_path, verbose_name='Picture')),
                ('contact_info', models.CharField(max_length=100)),
                ('neighborhood_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watch.neighborhood')),
            ],
        ),
    ]
