# Generated by Django 4.0.4 on 2022-06-21 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0016_remove_business_neighborhood_id_policeauthority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcentre',
            name='user',
        ),
        migrations.RemoveField(
            model_name='policeauthority',
            name='user',
        ),
    ]
