# Generated by Django 4.0.5 on 2022-06-21 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0020_business_neighborhood_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='neighborhood_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watch.neighborhood'),
        ),
    ]
